name: Delete Artifacts

on: [push, workflow_dispatch]


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: echo hello > world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt

      # delete-artifact
      - uses: geekyeggo/delete-artifact@v5.1.0
        with:
          name: my-artifact