name: 19 - Checkout Action

on:
  push:
    branches:
      - '*' # for all branches
      - '!dev' # Except the main branch
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
          date > report.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated checkout workflow file"
          git push
